<a href="https://colab.research.google.com/github/yosaarya/Data-Mining-A11.4623/blob/main/Pra_UAS_KB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
program = pd.read_csv('dataset.csv');
program.head(11)

gender  race/ethnicity  ...  reading score  writing score
0        0               2  ...             72             74
1        0               3  ...             90             88
2        0               2  ...             95             93
3        1               1  ...             57             44
4        1               3  ...             78             75
5        0               2  ...             83             78
6        0               2  ...             95             92
7        1               2  ...             43             39
8        1               4  ...             64             67
9        0               2  ...             60             50
10       1               3  ...             54             52

[11 rows x 8 columns]

In [ ]:
x = program.drop(["test preparation course"], axis = 1)
x.head(11)

gender  race/ethnicity  ...  reading score  writing score
0        0               2  ...             72             74
1        0               3  ...             90             88
2        0               2  ...             95             93
3        1               1  ...             57             44
4        1               3  ...             78             75
5        0               2  ...             83             78
6        0               2  ...             95             92
7        1               2  ...             43             39
8        1               4  ...             64             67
9        0               2  ...             60             50
10       1               3  ...             54             52

[11 rows x 7 columns]

In [ ]:
y = program["test preparation course"]
y.head(11)

0     1
1     3
2     1
3     1
4     1
5     1
6     3
7     1
8     3
9     1
10    1
Name: test preparation course, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.34, random_state = 123)

In [ ]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

In [ ]:
nbtrain = modelnb.fit(x_train, y_train)

In [ ]:
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 3, 3, 1, 1, 3, 3, 1, 1, 3,
       3, 1, 3, 3, 3, 3, 1, 1, 3, 1, 3, 3, 1, 1, 1, 1, 1, 1, 3, 1, 3, 3,
       3, 3, 1, 3, 1, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 3,
       3, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 3, 3, 3, 3, 3, 1, 1,
       3, 3, 1, 1, 1, 1, 3, 3, 3, 1, 3, 1, 1, 3, 3, 3, 1, 1, 3, 1, 1, 1,
       3, 1, 3, 1, 1, 1, 3, 1, 1, 3, 3, 3, 3, 1, 3, 3, 1, 1, 3, 3, 1, 1,
       1, 1, 3, 3, 1, 3, 3, 1, 1, 1, 3, 1, 3, 1, 3, 1, 1, 1, 1, 1, 3, 1,
       1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 1, 1,
       3, 1, 3, 1, 3, 3, 3, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
       3, 3, 1, 3, 1, 1, 3, 1, 1, 3, 3, 1, 1, 1, 3, 1, 3, 1, 1, 1, 3, 1,
       1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3,
       1, 1, 1, 1, 1, 1, 3, 1, 1, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 1, 3, 3,
       1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 3,
       1, 1, 3, 3, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1,

In [ ]:
nbtrain.predict_proba(x_test)

array([[9.82047643e-01, 1.79523569e-02],
       [6.95392455e-01, 3.04607545e-01],
       [9.15190328e-01, 8.48096722e-02],
       [5.11065826e-01, 4.88934174e-01],
       [7.24388166e-01, 2.75611834e-01],
       [4.43940650e-01, 5.56059350e-01],
       [3.89932575e-01, 6.10067425e-01],
       [9.37317725e-01, 6.26822749e-02],
       [5.77321111e-01, 4.22678889e-01],
       [5.39707226e-01, 4.60292774e-01],
       [8.91283614e-01, 1.08716386e-01],
       [3.16682860e-01, 6.83317140e-01],
       [7.58908171e-01, 2.41091829e-01],
       [3.98928324e-01, 6.01071676e-01],
       [4.77017461e-01, 5.22982539e-01],
       [9.98686317e-01, 1.31368313e-03],
       [9.06243985e-01, 9.37560155e-02],
       [4.08806134e-01, 5.91193866e-01],
       [2.74355343e-01, 7.25644657e-01],
       [5.72031678e-01, 4.27968322e-01],
       [5.12379387e-01, 4.87620613e-01],
       [2.58857504e-01, 7.41142496e-01],
       [1.37923049e-01, 8.62076951e-01],
       [9.96696529e-01, 3.30347072e-03],
       [9.428144

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test, y_pred)

array([[154,  72],
       [ 51,  63]])

In [ ]:
y_actual = pd.Series([1,3,1,1,1,1,3,1,3,1,1], name = "actual")
y_pred = pd.Series([1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 3, 3, 1, 1, 3, 3, 1, 1, 3,
       3, 1, 3, 3, 3, 3, 1, 1, 3, 1, 3, 3, 1, 1, 1, 1, 1, 1, 3, 1, 3, 3,
       3, 3, 1, 3, 1, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 3,
       3, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 3, 3, 3, 3, 3, 1, 1,
       3, 3, 1, 1, 1, 1, 3, 3, 3, 1, 3, 1, 1, 3, 3, 3, 1, 1, 3, 1, 1, 1,
       3, 1, 3, 1, 1, 1, 3, 1, 1, 3, 3, 3, 3, 1, 3, 3, 1, 1, 3, 3, 1, 1,
       1, 1, 3, 3, 1, 3, 3, 1, 1, 1, 3, 1, 3, 1, 3, 1, 1, 1, 1, 1, 3, 1,
       1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 1, 1,
       3, 1, 3, 1, 3, 3, 3, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
       3, 3, 1, 3, 1, 1, 3, 1, 1, 3, 3, 1, 1, 1, 3, 1, 3, 1, 1, 1, 3, 1,
       1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3,
       1, 1, 1, 1, 1, 1, 3, 1, 1, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 1, 3, 3,
       1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 3,
       1, 1, 3, 3, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1, 3,
       1, 1, 1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 1, 3, 1, 1, 1, 3, 1, 3, 1, 3,
       1, 1, 3, 3, 1, 1, 3, 3, 3, 3], name = "predict")
df_confusion = pd.crosstab(y_actual, y_pred)

In [ ]:
df_confusion

predict  1  3
actual       
1        7  1
3        2  1